"""empty message

Revision ID: 4d36bc28320a
Revises: b940ce8c40f4
Create Date: 2026-03-04 13:54:33.062645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d36bc28320a'
down_revision: Union[str, Sequence[str], None] = 'b940ce8c40f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###
