"""password extend

Revision ID: 7054852699a4
Revises: 93e4960340f3
Create Date: 2026-03-04 21:52:37.562710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7054852699a4'
down_revision: Union[str, Sequence[str], None] = '93e4960340f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
