"""enum_gender

Revision ID: 76e43d41f205
Revises: 7054852699a4
Create Date: 2026-03-05 10:27:46.859185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e43d41f205'
down_revision: Union[str, Sequence[str], None] = '7054852699a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MALE', 'FEMALE', name='gender').create(op.get_bind())
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('MALE', 'FEMALE', name='gender'),
               existing_nullable=False,
               postgresql_using="upper(gender)::gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    sa.Enum('MALE', 'FEMALE', name='gender').drop(op.get_bind())
    # ### end Alembic commands ###
