"""empty message

Revision ID: 93e4960340f3
Revises: 4d36bc28320a
Create Date: 2026-03-04 13:56:44.406090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e4960340f3'
down_revision: Union[str, Sequence[str], None] = '4d36bc28320a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename 'id' to 'user_id' instead of dropping and adding
    op.alter_column('users', 'id', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id', new_column_name='id')
    # ### end Alembic commands ###
