"""id upgade - user id to id, job id to id

Revision ID: a0719b2b0d24
Revises: 76e43d41f205
Create Date: 2026-03-10 15:17:01.456065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a0719b2b0d24'
down_revision: Union[str, Sequence[str], None] = '76e43d41f205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id', new_column_name='id')
    
    op.create_table('jobs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=150), nullable=False),
        sa.Column('salary', sa.Float(), nullable=False),
        sa.Column('office_address', sa.String(length=50), nullable=False),
        sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=False),
        sa.Column('cell_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.alter_column('users', 'id', new_column_name='user_id')
    # ### end Alembic commands ###
