"""empty message

Revision ID: b940ce8c40f4
Revises: 
Create Date: 2026-03-04 13:46:38.980352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b940ce8c40f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=1), nullable=False, server_default='M'))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False, server_default='example@test.com'))
    op.add_column('users', sa.Column('password', sa.String(length=8), nullable=False, server_default='password'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    
    # Remove server_default after adding columns
    op.alter_column('users', 'gender', server_default=None)
    op.alter_column('users', 'email', server_default=None)
    op.alter_column('users', 'password', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)

    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
